const DEFAULT_APPS = [
  {id:'a01',title:'LEARNING LAB',subtitle:'学びの実験室',icon:'flask-conical',image:'',color:'rose',category:'CORE',url:'#',visible:true},
  {id:'a02',title:'QUBE',subtitle:'クイズ作成ツール',icon:'box',image:'',color:'violet',category:'CORE',url:'#',visible:true},
  {id:'a03',title:'PDF LAB',subtitle:'PDFをもっと自由に',icon:'file-text',image:'',color:'coral',category:'TOOLS',url:'#',visible:true},
  {id:'a04',title:'3 HINTS QUIZ',subtitle:'3つのヒントで考える',icon:'lightbulb',image:'',color:'amber',category:'ENGLISH',url:'#',visible:true},
  {id:'a05',title:'MEMURO TANKEN',subtitle:'芽室たんけんマップ',icon:'map-pinned',image:'',color:'mint',category:'SCHOOL',url:'#',visible:true},
  {id:'a06',title:'ROULETTE PICKER',subtitle:'ランダムに選ぶ',icon:'circle-dot-dashed',image:'',color:'orange',category:'TOOLS',url:'#',visible:true},
  {id:'a07',title:'SPEECH STUDIO',subtitle:'音読・発音トレーニング',icon:'audio-lines',image:'',color:'sky',category:'ENGLISH',url:'#',visible:true},
  {id:'a08',title:'READING QUEST',subtitle:'読むってたのしい',icon:'book-open',image:'',color:'green',category:'ENGLISH',url:'#',visible:true},
  {id:'a09',title:'WORD BUILDER',subtitle:'英単語をつくろう',icon:'blocks',image:'',color:'sand',category:'ENGLISH',url:'#',visible:true},
  {id:'a10',title:'WRITING COACH',subtitle:'書く力を育てる',icon:'pencil-line',image:'',color:'lilac',category:'ENGLISH',url:'#',visible:true},
  {id:'a11',title:'LISTENING DECK',subtitle:'聞く力をのばす',icon:'headphones',image:'',color:'blue',category:'ENGLISH',url:'#',visible:true},
  {id:'a12',title:'DEBATE LAB',subtitle:'考えて、話し合う',icon:'messages-square',image:'',color:'rose',category:'ENGLISH',url:'#',visible:true},
  {id:'a13',title:'LESSON BOARD',subtitle:'授業を見える化する',icon:'presentation',image:'',color:'orange',category:'SCHOOL',url:'#',visible:true},
  {id:'a14',title:'FLASHCARD MAKER',subtitle:'フラッシュカード作成',icon:'layers-3',image:'',color:'rose',category:'SCHOOL',url:'#',visible:true},
  {id:'a15',title:'CLASS TIMER',subtitle:'授業タイマー',icon:'timer',image:'',color:'blue',category:'SCHOOL',url:'#',visible:true},
  {id:'a16',title:'STUDY TRACKER',subtitle:'学びの記録をつける',icon:'chart-no-axes-column-increasing',image:'',color:'green',category:'SCHOOL',url:'#',visible:true},
  {id:'a17',title:'PROMPT STUDIO',subtitle:'AI活用のヒント集',icon:'sparkles',image:'',color:'violet',category:'AI',url:'#',visible:true},
  {id:'a18',title:'CHORUS VISUALS',subtitle:'合唱をもっと楽しく',icon:'music-2',image:'',color:'aqua',category:'CREATE',url:'#',visible:true},
  {id:'a19',title:'RESEARCH NOTES',subtitle:'リサーチメモ',icon:'search-check',image:'',color:'blue',category:'IDEAS',url:'#',visible:true},
  {id:'a20',title:'APP ARCHIVE',subtitle:'つくったアプリ一覧',icon:'archive',image:'',color:'sand',category:'CORE',url:'#',visible:true},
  {id:'a21',title:'SLIDE MAKER',subtitle:'スライドをつくる',icon:'panel-top',image:'',color:'coral',category:'CREATE',url:'#',visible:true},
  {id:'a22',title:'QUIZ IMPORTER',subtitle:'問題を取り込む',icon:'cloud-upload',image:'',color:'sky',category:'TOOLS',url:'#',visible:true},
  {id:'a23',title:'SEAT PICKER',subtitle:'席をランダムに決める',icon:'armchair',image:'',color:'amber',category:'SCHOOL',url:'#',visible:true},
  {id:'a24',title:'IDEA BOX',subtitle:'やりたいことメモ',icon:'package-open',image:'',color:'rose',category:'IDEAS',url:'#',visible:true}
];
